services:
  mongodb:
    image: mongo
    container_name: crewchat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - crewchat_mongodb:/data/db
    restart: unless-stopped

  redis:
    image: redis
    container_name: crewchat-redis
    ports:
      - "6379:6379"
    volumes:
      - crewchat_redis:/data
    restart: unless-stopped

volumes:
  crewchat_mongodb:
  crewchat_redis:
