services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/web/.env.docker
    depends_on:
      - socket-server
      - mongo
    # volumes:
    #   - .:/app

  socket-server:
    build:
      context: .
      dockerfile: apps/socket-server/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - apps/socket-server/.env.docker
    depends_on:
      - redis
    # volumes:
    #   - .:/app

volumes:
  mongo_data:
